lang = "en"
host = "damianwilliamson.com"

[dependencies."std::core"]
version = "^5"

[dependencies."std::blueprint::default"]
version = "1.1.2"

[page.meta]
description = "Selected projects by Damian Williamson"
keywords = "Design, Architecture"
format-detection = "telephone=no"

[publish.aws]
region = "ap-southeast-1"
credentials = "uwe"

[publish.aws.environments.stage]
bucket = "stage.damianwilliamson.com"

[publish.aws.environments.production]
bucket = "damianwilliamson.com"
