lang = "en"
host = "damianwilliamson.com"

[dependencies."std::core"]
version = "^5"

[dependencies."std::blueprint::default"]
version = "1.1.2"

[page.meta]
description = "Selected projects by Damian Williamson"
keywords = "Design, Architecture"
